build_from:
  aarch64: debian:13.5-slim
  amd64: debian:13.5-slim
labels:
  org.opencontainers.image.title: "boinctui add-on"
  org.opencontainers.image.description: "Home Assistant boinctui add-on."
  org.opencontainers.image.source: "https://github.com/hectorespert/boinc-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
