name: boinctui
version: "1.0.0"
slug: boinctui
description: Fullscreen text mode manager for BOINC client
url: "https://github.com/hectorespert/boinc-addons/tree/main/boinctui"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 7681
panel_icon: mdi:console
codenotary: hectorespertpardo@gmail.com
image: "ghcr.io/hectorespert/{arch}-addon-boinctui"
apparmor: false
