build_from:
  aarch64: arm64v8/debian:12.9-slim
  amd64: amd64/debian:12.9-slim
  armhf: arm32v5/debian:12.9-slim
  armv7: arm32v7/debian:12.9-slim
  i386: i386/debian:12.9-slim
labels:
  org.opencontainers.image.title: "Boinc add-on"
  org.opencontainers.image.description: "Home Assistant Boinc add-on."
  org.opencontainers.image.source: "https://github.com/hectorespert/boinc-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary:
  signer: hectorespertpardo@gmail.com
