FROM ghcr.io/home-assistant/devcontainer:2-addons
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get --no-install-recommends -y install python3 python3-venv python3-pip python3-dict2xml bundler
