name: BOINC UI
version: "0.3.0"
slug: boincui
description: Graphical web interface to monitor and control the BOINC client
url: "https://github.com/hectorespert/boinc-addons/tree/main/boincui"
arch:
  - aarch64
  - amd64
init: false
ingress: true
panel_icon: mdi:chart-box
stage: experimental
schema:
  boinc_host: "str?"
  boinc_port: "port?"
  gui_rpc_password: "password?"
image: "ghcr.io/hectorespert/addon-boincui"
apparmor: false
backup: cold
