name: Build Add-ons

on:
  workflow_call:
    inputs:
      changed_addons:
        description: 'JSON array of add-ons to build'
        required: true
        type: string
      test_mode:
        description: 'Build in test mode (do not publish)'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ${{ fromJson(inputs.changed_addons) }}
        arch: ["aarch64", "amd64"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"

      - name: Check if add-on should be built
        id: check
        run: |
          if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
             echo "build_arch=true" >> $GITHUB_OUTPUT;
             echo "image=${{ steps.info.outputs.image }}" >> $GITHUB_OUTPUT;
           else
             echo "${{ matrix.arch }} is not a valid arch for ${{ matrix.addon }}, skipping build";
             echo "build_arch=false" >> $GITHUB_OUTPUT;
          fi

      - name: Set up Docker Buildx
        if: steps.check.outputs.build_arch == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder/actions/build-image@2026.06.0
        with:
          arch: ${{ matrix.arch }}
          image: ${{ steps.check.outputs.image }}
          image-tags: |
            ${{ steps.info.outputs.version }}
            latest
          version: ${{ steps.info.outputs.version }}
          container-registry: ghcr.io
          container-registry-username: ${{ github.repository_owner }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          push: ${{ inputs.test_mode == false && 'true' || 'false' }}
          cosign: true

      - name: Test boinc add-on
        if: matrix.addon == 'boinc' && steps.check.outputs.build_arch == 'true'
        working-directory: boinc
        run: |
          if [[ "${{ inputs.test_mode }}" == "true" ]]; then
            IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${{ matrix.arch }}-addon-boinc:latest"
          else
            IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${{ matrix.arch }}-addon-boinc:${{ steps.info.outputs.version }}"
          fi

          docker run --uts=host --pid=host --rm \
            -v boinc_test_${{ matrix.arch }}:/data \
            -v $(pwd)/operator/options.json:/data/options.json:ro \
            "${IMAGE_TAG}" \
            --log-level DEBUG \
            --exit-immediately true
