name: BOINC Operator tests

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dict2xml
    - name: Run tests
      working-directory: boinc/operator
      run: |
        python -m unittest discover -s test -t test
