name: Release

on:
  push:
    branches:
      - main

jobs:
  find_changed:
    uses: ./.github/workflows/find-changed-addons.yaml
    with:
      monitored_files: 'build.yaml config.yaml Dockerfile operator'

  check_version:
    needs: find_changed
    if: needs.find_changed.outputs.changed == 'true'
    uses: ./.github/workflows/check-version.yaml
    with:
      changed_addons: ${{ needs.find_changed.outputs.changed_addons }}
      strict_check: true

  build:
    needs: [find_changed, check_version]
    if: needs.find_changed.outputs.changed == 'true'
    uses: ./.github/workflows/build-addons.yaml
    with:
      changed_addons: ${{ needs.find_changed.outputs.changed_addons }}
      test_mode: false
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_release:
    needs: [find_changed, build, check_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: needs.find_changed.outputs.changed == 'true'
    name: Create release for ${{ matrix.addon }}
    strategy:
      matrix:
        addon: ${{ fromJson(needs.find_changed.outputs.changed_addons) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up yq
        uses: mikefarah/yq@v4

      - name: Get addon version
        id: version
        run: |
          VERSION=$(yq e '.version' ${{ matrix.addon }}/config.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${{ matrix.addon }}-v$VERSION" >> $GITHUB_OUTPUT
          echo "Creating release: ${{ matrix.addon }}-v$VERSION"

      - name: Read CHANGELOG
        id: changelog
        run: |
          if [ -f "${{ matrix.addon }}/CHANGELOG.md" ]; then
            VERSION="${{ steps.version.outputs.version }}"
            # Extract the section for this version from CHANGELOG
            CHANGELOG_CONTENT=$(awk -v ver="$VERSION" '
              $0 ~ "^## " ver {flag=1; next}
              /^## [0-9]/ && flag {exit}
              flag {print}
            ' "${{ matrix.addon }}/CHANGELOG.md" | sed '/^$/d' || true)
            
            if [ -z "$CHANGELOG_CONTENT" ]; then
              CHANGELOG_CONTENT="No changelog available for this version."
            fi
          else
            CHANGELOG_CONTENT="No changelog file found."
          fi
          
          # Save changelog to file for multiline content
          echo "$CHANGELOG_CONTENT" > /tmp/changelog.txt

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ steps.version.outputs.tag }}" -m "Release ${{ matrix.addon }} version ${{ steps.version.outputs.version }}"
          git push origin "${{ steps.version.outputs.tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ matrix.addon }} v${{ steps.version.outputs.version }}
          body_path: /tmp/changelog.txt
          draft: false
          prerelease: false
          generate_release_notes: true
